### PR TITLE
permission checks on triggers 

### PR DESCRIPTION
**Pull request by Dev-Shaz**

### CODE REVIEW

**Comment by XiosBombay** [comment]
@IDKThatGuy Did you test people without ranks getting a no perms notification?

**Comment by XiosBombay** [comment]
I'll test the code after. Right now I only have that question.

**Comment by IDKThatGuy** [comment]
> @IDKThatGuy Did you test people without ranks getting a no perms notification?

I put permission checks so cheaters/modders cant trigger the event using a lua executor

**Comment by XiosBombay** [comment]
I know. But I meant if you tested what notifications do other people get if they're not mods

**Comment by IDKThatGuy** [comment]
No i didnt bother

**Comment by XiosBombay** [comment]
Since I'm working on V2. This will be closed. It will be kept in mind though.

**Pull request closed without merging**
